package dev.pirc.android.core.timeline

import dev.pirc.android.core.PircJson
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The shared golden cases in `fixtures/timeline`, generated by the web client:
 * this port must turn the same snapshot and events into the same timeline.
 */
class TimelineFixturesTest {
    private val dir = File(System.getProperty("pirc.fixtures") ?: "../../../fixtures", "timeline")
    private val clock = { 1_000_000_000L }

    @Test
    fun matchesTheWebClient() {
        val files = dir.listFiles { file -> file.extension == "json" }.orEmpty().sortedBy { it.name }
        assertTrue("no fixtures in $dir", files.isNotEmpty())
        for (file in files) {
            val fixture = PircJson.parseToJsonElement(file.readText()) as JsonObject
            val expected = fixture["expected"] as JsonObject
            var state = snapshotState(fixture["snapshot"]!!, clock)
            assertEquals("${file.name}: after the snapshot", expected["afterSnapshot"], project(state))
            for (raw in fixture["events"] as JsonArray) state = state.reduce(normalizeEvent(raw, clock), clock)
            assertEquals("${file.name}: after the events", expected["afterEvents"], project(state))
        }
    }

    private fun JsonObject.Companion.of(vararg pairs: Pair<String, JsonElement?>) =
        JsonObject(pairs.filter { it.second != null }.associate { it.first to it.second!! })

    private fun str(value: String?) = value?.let(::JsonPrimitive)
    private fun flag(value: Boolean) = if (value) JsonPrimitive(true) else null
    private fun count(size: Int) = if (size > 0) JsonPrimitive(size) else null

    private fun tool(item: ToolCall): JsonObject = JsonObject.of(
        "id" to str(item.id),
        "name" to str(item.name),
        "status" to str(item.status),
        "input" to item.input,
        "output" to str(item.output),
        "diff" to str(item.diff),
        "images" to count(item.images.size),
        "operations" to item.operations.takeIf { it.isNotEmpty() }?.let { operations -> JsonArray(operations.map(::tool)) },
    )

    private fun message(message: Message) = JsonObject.of(
        "id" to str(message.id),
        "role" to str(message.role),
        "content" to str(message.content),
        "isPartial" to flag(message.isPartial),
        "thinking" to str(message.thinking),
        "thinkingRedacted" to flag(message.thinkingRedacted),
        "stopReason" to str(message.stopReason),
        "errorMessage" to str(message.errorMessage),
        "model" to str(message.model),
        "systemKind" to str(message.systemKind),
        "level" to str(message.level),
        "label" to str(message.label),
        "meta" to str(message.meta),
        "images" to count(message.images.size),
        "tools" to message.tools.takeIf { it.isNotEmpty() }?.let { tools -> JsonArray(tools.map(::tool)) },
    )

    /** Mirrors `project` in `apps/web/src/lib/timeline-fixtures.test.ts`. */
    private fun project(state: SessionState) = buildJsonObject {
        put("cursor", state.cursor)
        put("runnerEpoch", state.runnerEpoch)
        put("needsSnapshot", state.needsSnapshot)
        put("sessionName", state.session.name)
        put("pinned", state.session.pinned)
        put("runStatus", state.run?.status?.let(::JsonPrimitive) ?: JsonNull)
        put("runnerStatus", state.runnerStatus)
        put("selectedModelId", state.selectedModelId?.let(::JsonPrimitive) ?: JsonNull)
        put("thinkingLevel", state.thinkingLevel?.let(::JsonPrimitive) ?: JsonNull)
        put("queue", buildJsonArray { state.queue.forEach { add(JsonPrimitive("${it.kind}:${it.content}")) } })
        put("widgets", JsonObject(state.widgets.mapValues { (_, lines) -> JsonArray(lines.map(::JsonPrimitive)) }))
        put("statuses", JsonObject(state.statuses.mapValues { (_, text) -> JsonPrimitive(text) }))
        put(
            "interactions",
            JsonArray(
                state.interactions.map { item ->
                    JsonObject.of(
                        "id" to str(item.id),
                        "kind" to str(item.kind),
                        "toolCallId" to str(item.toolCallId),
                        "title" to str(item.title),
                        "description" to str(item.description),
                        "status" to str(item.status),
                        "multiple" to flag(item.kind == "select" && item.multiple),
                        "options" to if (item.kind == "select") JsonArray(
                            item.options.map { JsonObject.of("value" to str(it.value), "description" to str(it.description)) },
                        ) else null,
                    )
                },
            ),
        )
        put("messages", JsonArray(state.messages.map(::message)))
    }
}
